Basic movement
MrJackey/Were.Wolf pull request #1
Opened 2020-11-18 12:39 UTC by MrJackey

## Summary
Fixes #6.
Added basic movement to the player, enabling moving left and right.
Added jump functionality to the player.
The player currently has no friction to prevent sticking to walls.

## Visualisation
![98yARNlhMt](https://user-images.githubusercontent.com/44698252/99517155-56e76700-298f-11eb-893c-d438bd90ef8f.gif)

2020-11-18 14:23 UTC, smeas requested changes

2020-11-18 14:23 UTC, smeas commented on Assets/Scripts/Player/PlayerController.cs
> +		if (Input.GetButtonDown("Jump") && isGrounded)
It's cheaper to check the bool before checking the input.
```suggestion
		if (isGrounded && Input.GetButtonDown("Jump"))
```

2020-11-18 14:23 UTC, smeas commented on Assets/Scripts/Player/PlayerController.cs
> +		int floorLayer = LayerMask.GetMask("Ground");
You should either cache the layer mask value, or make a serialized `LayerMask` field so you can select the layer from the inspector.

2020-11-18 14:23 UTC, smeas commented on Assets/Scripts/Player/PlayerController.cs
> +		return hit.collider;
Please use explicit null check on unity objects.
```suggestion
		return hit.collider != null;
```

2020-11-18 14:40 UTC, smeas approved these changes

2020-11-19 08:10 UTC, smeas approved these changes

2020-11-19 09:25 UTC, Addehman approved these changes
Looking good to me!

2020-11-19 09:29 UTC, merged