320 Fade music volume between level transitions
MrJackey/Were.Wolf pull request #127
Opened 2021-01-01 14:07 UTC by smeas

2021-01-01 15:35 UTC, MrJackey requested changes
Tiny possible unnecessary picky thing. Otherwise seems to work well

2021-01-01 15:35 UTC, MrJackey commented on Assets/Scripts/Audio/LevelMusicPlayer.cs
> +	private void Play(AudioClip track, bool allowFade) {
Where do you use allowFade? Can't find any.

2021-01-04 09:19 UTC, Addehman approved these changes
Noice!

2021-01-04 09:20 UTC, MrJackey approved these changes
:shipit:

2021-01-04 09:21 UTC, merged