Disables airjump and dash while human
MrJackey/Were.Wolf pull request #27
Opened 2020-11-24 15:14 UTC by MrJackey

## Summary
Fixes # 54
Toggles a variable depending on if transforming to human.
This disables air jumps and dash.

2020-11-24 16:01 UTC, smeas requested changes

2020-11-24 16:01 UTC, smeas commented on Assets/Scripts/Player/PlayerController.cs
>  	public bool AllowControls { set => allowControls = value; }
Inconsistent formatting of properties.

2020-11-24 16:29 UTC, MrJackey commented on Assets/Scripts/Player/PlayerController.cs
>  	public bool AllowControls { set => allowControls = value; }
True, will fix

2020-11-24 17:52 UTC, smeas approved these changes
+1, Great!

2020-11-25 09:11 UTC, Addehman approved these changes
Ser gytt!

2020-11-25 14:50 UTC, smeas approved these changes

2020-11-25 14:51 UTC, merged