Transformation #7
MrJackey/Were.Wolf pull request #3
Opened 2020-11-18 13:08 UTC by Addehman

Uploading the script for Transforming the player character from werewolf to human.

Transform by holding "R"-key for 1.2 seconds which completes the transformation into human form. After 5 seconds it will return to the werewolf form again.

2020-11-18 13:26 UTC, MrJackey requested changes
Looking good, just a lot of debug which maybe should be removed

2020-11-18 13:26 UTC, MrJackey commented on Assets/Scripts/Transformation.cs
> +    //[SerializeField] private bool isTransformed = false;
Is this comment required to exist? Do we need it?

2020-11-18 13:26 UTC, MrJackey commented on Assets/Scripts/Transformation.cs
> +			Debug.Log("Transformation process Charging...");
Do you think debug logging should be kept?

2020-11-18 13:36 UTC, smeas requested changes
Just some formatting/style issues.

There is mixed whitespace (spaces/tabs) in the whole file.

2020-11-18 13:36 UTC, smeas commented on Assets/Scripts/Transformation.cs
> +    //[SerializeField] private bool isTransformed = false;
Brace should be on the same line.

2020-11-18 13:36 UTC, smeas commented on Assets/Scripts/Transformation.cs
> +
Remove empty line at start of method.

2020-11-18 13:36 UTC, smeas commented on Assets/Scripts/Transformation.cs
> +	private IEnumerator HumanFormDuration() {
Use 'Co' prefix for coroutine?

2020-11-18 14:06 UTC, Addehman reviewed
Applied the changes! thanks for the reviews!

2020-11-18 14:06 UTC, Addehman commented on Assets/Scripts/Transformation.cs
> +    //[SerializeField] private bool isTransformed = false;
Ah nope!

2020-11-18 14:06 UTC, Addehman commented on Assets/Scripts/Transformation.cs
> +    //[SerializeField] private bool isTransformed = false;
ah ofc!

2020-11-18 14:06 UTC, Addehman commented on Assets/Scripts/Transformation.cs
> +			Debug.Log("Transformation process Charging...");
consider them gone!

2020-11-18 14:06 UTC, Addehman commented on Assets/Scripts/Transformation.cs
> +
done!

2020-11-18 14:06 UTC, Addehman commented on Assets/Scripts/Transformation.cs
> +	private IEnumerator HumanFormDuration() {
ah! right! thanks!

2020-11-18 14:30 UTC, MrJackey requested changes
Just one question, otherwise looks good

2020-11-18 14:30 UTC, MrJackey commented on Assets/Scripts/Transformation.cs
> +    	if (transStates == TransformationStates.Transforming) {
Are you sure this should be .Transforming? Shouldn't this remain as .Wolf?

2020-11-18 14:30 UTC, MrJackey commented on Assets/Scripts/Transformation.cs
> +		transStates = TransformationStates.Transforming;
What about having this as a boolean instead? Would be more generic if you could see if transforming and keep it from a middle. Might depend on if the human to wolf transformation should be instant.

2020-11-18 20:26 UTC, smeas requested changes
BUG: If you transform to wolf>human>wolf>human you get a shorter human form duration.
The problem is that the `CoHumanFormDuration` from the previous transformation is still running .

2020-11-18 20:26 UTC, smeas commented on Assets/Scripts/Transformation.cs
> +		}
Duplicate code in if statement blocks. The only difference is what color you set so you only need to check when you set the color.
```suggestion
		mySpriteRend.color = transformingColor;

		for (transTimer = transDuration; transTimer > 0 ; transTimer -= Time.deltaTime) {
			if (Input.GetKeyUp(KeyCode.R)) {
				if (transStates == TransformationStates.Wolf)
					mySpriteRend.color = wolfColor;
				else if (transStates == TransformationStates.Human)
					mySpriteRend.color = humanColor;

				yield break;
			}
			yield return null;
		}
```

2020-11-18 20:26 UTC, smeas commented on Assets/Scripts/Transformation.cs
> +
Remove empty line in the middle of if-else chain.

2020-11-18 21:01 UTC, smeas approved these changes

2020-11-19 09:41 UTC, MrJackey approved these changes
+1

2020-11-19 10:26 UTC, smeas approved these changes

2020-11-19 10:26 UTC, merged