$89 damage effect
MrJackey/Were.Wolf pull request #47
Opened 2020-11-30 13:27 UTC by MrJackey

## Summary
Fixes $89
Created blood damage effect.
Spikes now create blood damage effect on player hit.

## Visualisation
![coDeq2hXM0](https://user-images.githubusercontent.com/44698252/100615524-fe618380-3317-11eb-85e8-de4c464feced.gif)

2020-11-30 17:06 UTC, smeas requested changes

2020-11-30 17:06 UTC, smeas commented on Assets/Scripts/Common/DamageArea.cs
> +				onDamageEffect.Invoke(new Vector2(xValue / i, yValue / i));
And maybe extract this into a separate method. `DoEffect` or something?
```suggestion
			if (!other.attachedRigidbody.CompareTag(effectTarget)) return;

			int contactCount = other.GetContacts(contacts);
			if (contactCount != 0) {
				Vector2 averageContact = new Vector2();
				int num = 0;

				for (int i = 0; i < contactCount; i++) {
					ContactPoint2D contact = contacts[i];
					if (contact.collider.gameObject != gameObject) continue;

					averageContact += contact.point;
					num++;
				}

				averageContact /= num;
				onDamageEffect.Invoke(averageContact);
			}
```

2020-11-30 17:06 UTC, smeas commented on Assets/Scripts/Common/Effects/DamageEffect.cs
> +		GetComponent<DamageArea>().OnDamageEffect.AddListener(Spawn);
Will likely never be a problem, but the fact that this listener is never removed makes me anxious.

2020-11-30 17:06 UTC, smeas commented on Assets/Scripts/Common/Effects/ParticleCleanUp.cs
> +	private new ParticleSystem particleSystem;
Why is this even a field?

2020-11-30 18:40 UTC, smeas requested changes

2020-11-30 18:40 UTC, smeas commented on Assets/Scripts/Common/DamageArea.cs
>  		}
You're looping through all 10 items in the array regardless of `contactCount`. Old entries in the array will still be considered and can affect the calculation.

2020-11-30 19:28 UTC, smeas approved these changes
Cool!

2020-12-01 09:38 UTC, Addehman approved these changes
I bloody approve!

2020-12-01 09:38 UTC, merged