$81 knockback
MrJackey/Were.Wolf pull request #52
Opened 2020-12-01 10:50 UTC by MrJackey

## Summary
Fixes 81
Objects can now be knockbacked by spikes if they have the knockbackable component.
Also fixed the transfoms components of the player prefab.

## Visualisation
![EBztMVYnpQ](https://user-images.githubusercontent.com/44698252/100731233-6ae98a80-33cb-11eb-91b7-8c4094c7dc7b.gif)

2020-12-01 16:09 UTC, smeas requested changes

2020-12-01 16:09 UTC, smeas commented on Assets/Scripts/Common/DamageArea.cs
>  			if (other.attachedRigidbody.CompareTag(effectTarget))
```suggestion
			if (effectTarget.Length != 0 && other.attachedRigidbody.CompareTag(effectTarget))
```

2020-12-01 16:09 UTC, smeas commented on Assets/Scripts/Common/DamageArea.cs
> +	private void CalculateAvgContact(Collider2D other, out Vector2 avg) {
Why is `avg` an out parameter, can't you just return it?

2020-12-01 16:09 UTC, smeas commented on Assets/Scripts/Common/Knockbackable.cs
> +		knockbackRoutine = StartCoroutine(CoKnockbackDuration(duration));
`knockbackDurationRoutine` would be a better name.

2020-12-01 18:00 UTC, Addehman reviewed
Is there anything forcing the player to be facing the same direction that the player was travelling in when entering a damageArea? Thinking this might be important for creating the feeling of being pushes/knocked backwards?

2020-12-02 08:18 UTC, smeas approved these changes
:+1:

2020-12-02 13:16 UTC, merged