$ 98 - Interactable Highlight Arrow
MrJackey/Were.Wolf pull request #55
Opened 2020-12-01 22:00 UTC by Addehman

Now an arrow appears and hovers over interactable items!

2020-12-01 22:41 UTC, Addehman commented
BUG: If the Box is placed beside the Lever, both their InteractArrows won't be removed, and a "MissingReferenceException" pops up. The Interact system needs to prioritize them, so for example it only sees the Box when also the Lever is present. Or, checks which object's center is closer to the player's center.

2020-12-02 07:34 UTC, MrJackey requested changes
Some minor things, I believe only letting the player interact with the closest item should also resolve that bug.

2020-12-02 07:34 UTC, MrJackey commented on Assets/Scripts/UI/InteractArrow.cs
> +			bobCurrent -= bobSpeed * Time.deltaTime;
Why are you using a boolean here? Couldn't you just do the following?
```suggestion
		if (bobCurrent <= bobStart)
			bobCurrent += bobSpeed * Time.deltaTime;
		else if (bobCurrent >= bobEnd)
			bobCurrent -= bobSpeed * Time.deltaTime;
```

2020-12-02 07:34 UTC, MrJackey commented on Assets/Scripts/Player/PlayerHandDetection.cs
> +	[SerializeField] private GameObject interactArrow;
Instead of letting the playerhand monitor the interact arrow, would it be better to let the interactable item handle it themselves?

2020-12-02 20:02 UTC, smeas requested changes
The arrow should probably not appear when carrying an item.

2020-12-02 20:02 UTC, smeas commented on Assets/Scripts/UI/InteractArrow.cs
> +	//[SerializeField] private AnimationCurve
```suggestion
```

2020-12-02 20:02 UTC, smeas commented on Assets/Scripts/Player/PlayerHandDetection.cs
> +	private float lowestDistance = 0;
This has no reason to be a field. Just make it a local variable in `SetClosestItem`.

2020-12-02 20:02 UTC, smeas commented on Assets/Scripts/Player/PlayerHandDetection.cs
>  	}
Cleaned it up a bit.
```suggestion
	private void SetClosestItem() {
		float lowestDistance = float.PositiveInfinity;
		Interactable closestItem = null;

		foreach (Interactable interactable in interactableList) {
			float distance = (transform.position - interactable.transform.position).sqrMagnitude;

			if (distance < lowestDistance) {
				lowestDistance = distance;
				closestItem = interactable;
			}
		}

		if (closestItem == null)
			return;

		interactArrow.transform.position = closestItem.transform.position + new Vector3(0, closestItem.InteractableArrowHeight, 0);
		interactArrowScript.Initialize();
		detectedInteractItem = closestItem;
	}
```

2020-12-03 12:55 UTC, smeas approved these changes
Nice work!
<img src="https://user-images.githubusercontent.com/8546813/101018772-44168a00-356c-11eb-9fea-3f6cf538d7f5.png" height="120">

2020-12-03 12:59 UTC, MrJackey commented on Assets/Scripts/Player/PlayerHandDetection.cs
> +			}
Can't this be changed?
```suggestion
detectedInteractItem = null;
			if (interactableList.Count == 0)
				interactArrow.SetActive(false);
```

2020-12-03 13:43 UTC, MrJackey approved these changes

2020-12-03 13:43 UTC, merged