Feature/124 scene transition
MrJackey/Were.Wolf pull request #69
Opened 2020-12-08 10:32 UTC by MrJackey

## Summary
Fixes 124
Added scene transition animation
Now uses transition where relevant

2020-12-08 15:56 UTC, smeas requested changes

2020-12-08 15:56 UTC, smeas commented on Assets/Scripts/UI/SceneTransitionHelper.cs
> +	}
Please fix.

2020-12-08 19:16 UTC, smeas approved these changes
Awesomesauce!

2020-12-09 08:29 UTC, Addehman approved these changes
Looking good!

2020-12-09 08:29 UTC, merged