162 Watcher AI update
MrJackey/Were.Wolf pull request #75
Opened 2020-12-09 15:48 UTC by smeas

orka

### TODO
- Tweak values

2020-12-09 20:50 UTC, Addehman approved these changes
Looks good enough to me 😄

2020-12-10 09:03 UTC, MrJackey requested changes
A few questions in the code: The ai does seem to work fine during testing atleast so great job!

2020-12-10 09:03 UTC, MrJackey commented on Assets/Scripts/Enemy/Watcher.cs
> +	private bool CheckPlayerVisible(out GameObject go) {
Why does it take an out variable here? I can't find it being used anywhere

2020-12-10 09:03 UTC, MrJackey commented on Assets/Scripts/Enemy/Watcher.cs
> +	private bool isPlayerVisible;
These names are a bit confusing, especially since isPlayerVisible seems to be the only mostly used.

2020-12-10 09:03 UTC, MrJackey commented on Assets/Scripts/Enemy/Watcher.cs
> +		playerTransform.GetComponent<Transformation>().AllowTransformation = false;
Maybe cache these ones as you did with player health? Same with OnLost below

2020-12-10 11:11 UTC, MrJackey approved these changes
Woohoo

2020-12-10 11:12 UTC, merged